### ISSUE TITLE
MerchantReturnPolicy & OfferShippingDetails types for Offer Properties hasMerchantReturnPolicy & shippingDetails

### ISSUE THREAD

**Issue by aksenovaa** [brotkrueml/schema#112]
Google's new guidelines for presenting Offer in search results concern the indication of properties:
https://developers.google.com/search/docs/appearance/structured-data/product#shipping
shippingDetails of type OfferShippingDetails

https://developers.google.com/search/docs/appearance/structured-data/product#returns
hasMerchantReturnPolicy of the type MerchantReturnPolicy

These types are not currently implemented

**Comment by brotkrueml** [comment]
EXT:schema comes with the core vocabulary (current version with schema.org 15.0, released on 2022-10-25). There are other vocabularies, in your case the pending one is relevant.

The properties you mentioned are pending:
- https://schema.org/shippingDetails
- https://schema.org/hasMerchantReturnPolicy

This means, they can change any time (/which would break a site possibly with a minor EXT:schema update). So you have two possibilities:

- Use [EXT:schema_pending ](https://extensions.typo3.org/extension/schema_pending)(which provides a load of properties and types)
- [Create an event listener](https://docs.typo3.org/p/brotkrueml/schema/2.7/en-us/Developer/Events.html#event-register-additional-properties) which adds those properties

I suggest to use the second suggestion, this way everything is under your control.

When schema.org integrates the two properties into the core vocabulary, they will be available also in EXT:schema.

See also: https://docs.typo3.org/p/brotkrueml/schema/2.7/en-us/Introduction/Index.html#the-schema-org-vocabulary
