### ISSUE TITLE
Exclude hidden pages from automatic breadcrumb generation

### ISSUE THREAD

**Issue by dahaupt** [brotkrueml/schema#114]
### Current behavior

A hidden page is added as `itemListElement` without `@id` which is reported as an issue in Google Search Console.

### Expected behavior/output

Exclude hidden pages in the breadcrumb structure

### Environment

- schema version: 2.8.0
- TYPO3 version: 11.5.27

**Comment by dahaupt** [comment]
Will provide a patch later on.

**Comment by brotkrueml** [comment]
@dahaupt Thanks for the report. It is fixed in the upcoming 2.9.0 release.
