### ISSUE TITLE
Update documentation about josn-ld position in sourcecode

### ISSUE THREAD

**Issue by vb-benjamin-eyring** [brotkrueml/schema#122]
### Is your feature request related to a problem? Please describe.

I had the problem, that during implementing the schema-viewhelper in a partial I was looking at that part of my sourcecode to find the json-ld I created. I didn't find it.

### Describe the solution you'd like

Just one sentence in the documentation about viewhelpers, that the json-ld will be placed at the end before the body tag (or is it  already there and I missed it?) - and not at the place where the viewhelper is placed.

### Describe alternatives you've considered

none, as solution has small effort.

### Teachability, Documentation, Adoption, Migration Strategy

none

### Additional context

none

**Comment by brotkrueml** [comment]
Actually, it is a configuration option:
https://docs.typo3.org/p/brotkrueml/schema/3.6/en-us/Configuration/Index.html#configuration-embedMarkupInBodySection
The default is to place it in the head section of the page.
