### ISSUE TITLE
Add Schema type: Schedule

### ISSUE THREAD

**Issue by YinYangDD** [brotkrueml/schema#125]
### Problem description
In order to create a regular time series for an `EducationEvent` I would like to use the field `eventSchedule`.
This field is based on data type `Schedule`
https://schema.org/eventSchedule
https://schema.org/Schedule

### Describe the solution you'd like
Please add field `eventSchedule` to `EducationEvent` and add type `Schedule` to schema extension.

Not urgent (I'm using startDate / endDate for the moment) but would be great to add it.
Used version: v3.7.1

**Comment by brotkrueml** [comment]
`eventSchedule` and `Schedule` are part of the pending vocabulary (recognisable with the blue colour). See also the introduction in the docs:
https://docs.typo3.org/p/brotkrueml/schema/3.7/en-us/Introduction/Index.html#vocabulary

You have two possibilities to get these terms into your installation:
1. The quick way: Use the [schema_pending](https://extensions.typo3.org/extension/schema_pending). This adds many, many terms from pending, most of them you won't need.
2. The resourceful way: [Extend the vocabulary on your own](https://docs.typo3.org/p/brotkrueml/schema/3.7/en-us/Developer/ExtendingVocabulary.html). You add only those terms you really need.

Additionally, the classes are generated automatically from the schema.org definition. The definition is updated a few times in the year. If a new definition is released, the classes are also updated.
