### ISSUE TITLE
Multiple Items in mainEntity

### ISSUE THREAD

**Issue by Andreas-Sommer** [brotkrueml/schema#25]
While using the API could not add multiple Question Objects in FAQPage on property mainEntity as suggested at https://developers.google.com/search/docs/data-types/faqpage

**Comment by Andreas-Sommer** [comment]
[Bugfix] comparison of mainEntity as AbstractType fail in case of type array
https://github.com/belsignum/schema/commit/e203de325e467211f8f72cd57e202fdf1d6c88a6

**Comment by brotkrueml** [comment]
Thanks for the hint, I will provide a bugfix release in the next days.
