### ISSUE TITLE
Schema data gets lost when non cached plugin on page

### ISSUE THREAD

**Issue by brotkrueml** [brotkrueml/schema#27]
When mixing a cached plugin on a page that creates schema data and a non cached plugin, the schema data is only visible the first time the page is called. If the page is called consecutively, the schema data from this plugin is no longer available. This is because the cached plugin is only called on the first hit and so only then the schema data is added.

**Comment by brotkrueml** [comment]
Ping @Kephson

**Comment by Kephson** [comment]
Hi, @brotkrueml could you follow my problem? If not I will try to setup a system which is showing the problem. As example we used the extension [cookies](https://extensions.typo3.org/extension/cookies)  from TER which is using USER_INT to add the plugin to a page.
The schema was created in the single view of an Extbase extension with a cached action.
We think the following will be done by the system:
**First page view before caching the page**
- Action is triggered and controller executed
- PageRenderer gets the data from the Controller
- schema.org is available in the page

**Second page view**
- Page is loaded from caching
- Controller is not executed
- PageRenderer is not cached and tries to get the data
- schema.org is not available in the page (only the schema.org which is inserted by the Middleware)

**Comment by brotkrueml** [comment]
Yes, I can reproduce the behaviour, thank you.
