### ISSUE TITLE
Add Signal/PSR-14 event to decide about embedding of markup

### ISSUE THREAD

**Issue by mhirdes** [brotkrueml/schema#29]
Hey. First of all you did an amazing job. Thank you a lot for that.

I struggle with the issue #18 

You're fully right to exlcde the schema from pages with no_index, but in the case of detail pages, e.g. for news articles or events it is different. We allways set the detail page to no_index, because we want to exclude the page without any uid parameter from the sitemap.xml. But if a parameter for a single article is given, the page is to index and also the JSON-LD should be shown.

It would be great to have a way as a developer to adjust or override the isIndexed settings.

Can you agree to this?

Kind Regards,
Marc

**Comment by brotkrueml** [comment]
Hi Marc,

thanks for your kind words.

You've got a point I haven't thought about it. I'm redirecting the pages without an uid parameter to the list page, so for me that doesn't matter.

I see some possibilities to achieve this:

1. Introduce a configuration setting "Embed markup on pages which are defined as no_index". This does no harm but highers a little bit the page load. This then applies to all pages of the TYPO3 installation.
2. Introduce a signal/PSR-14 event, so you can define yourself on which condition (page uids/languages/doktypes/user agent/etc.) the markup should be embedded. This would then be independent of no_index.
3. Introduce a TypoScript setting to override this behaviour. With conditions it could be as powerful as the signal/PSR-14 one.
4. Introduce a new page property "Embed markup" with the options "default" (like now), "yes" (which would overrule the no_index) and "no" (which is an addition to no_index, but I don't know a usecase for that).

For now I tend to point 1. Configuration settings are introduced and it is easy to (de)activate the feature. Point 2 is like taking a sledgehammer to crack a nut. For point 3, TypoScript is not used for now, this would introduce a new layer. With Point 4 an editor can possibly choose (according to the access rights) which seems not to be right.

I have to think about it. Do you see other possibilities? Would Point 1 be enough for you use case?

**Comment by opi99** [comment]
For documentation, if you like to set your own rule here you should add your EventListener after the one from Schema.org

```
after: 'ext-schema/embedMarkupDependingOnNoIndexPageField'
```

**Comment by brotkrueml** [comment]
@opi99 Thanks for the hint, I added it to the documentation for the 1.x branch. However, the markup will be embedded by default to noindex pages in the upcoming version 2.0, see #60.
