### ISSUE TITLE
Example in README

### ISSUE THREAD

**Issue by vergissberlin** [brotkrueml/schema#30]
**Hi @brotkrueml !**

It would be nice if you add an example of how to use it properly to the documentation.
Thank you!
André

**Comment by brotkrueml** [comment]
Hi André,
what are you missing? The documentation should be fairly comprehensive:
https://docs.typo3.org/p/brotkrueml/schema/master/en-us/Developer/Index.html

**Comment by brotkrueml** [comment]
Closed for lack of feedback.
