### ISSUE TITLE
add educationRequirements in JobPosting

### ISSUE THREAD

**Issue by davdenic** [brotkrueml/schema#50]
Hello, is it possible to add 
educationRequirements to
JobPosting ?
thanks

**Comment by brotkrueml** [comment]
The extension provides the schema.org core vocabulary. educationRequirements is still pending (https://schema.org/educationRequirements) - that means, it can be renamed or abandoned - or taken over into the core vocabulary. This is due the fact, the schema extension doesn't want to break anything with a future schema.org update (approx. every month).

But you can add the property on your own to your site with a slot or event listener, have a look at:
https://docs.typo3.org/p/brotkrueml/schema/1.7/en-us/Developer/Events.html#register-additional-properties-for-a-type
So you have it under your control independently from the schema.org core updates.

When the property is available in the core vocabulary, the slot/event listener can be removed - but it doesn't harm if it still added.

Does that help you?

**Comment by davdenic** [comment]
Thanks, it works.
May i suggest a small change in the documentation? 

in the example for version 9

```
$signalSlotDispatcher->connect(
   \Brotkrueml\Schema\Core\Model\AbstractType::class,
   'registerAdditionalTypeProperties',
   \Brotkrueml\Schema\EventListener\AdditionalPropertiesForPerson::class,
   '__invoke'
);

```
could be instead

```
$signalSlotDispatcher->connect(
   \Brotkrueml\Schema\Core\Model\AbstractType::class,
   'registerAdditionalTypeProperties',
   \YourVendor\YourExtension\Slot\AdditionalPropertiesForPerson::class,
   '__invoke'
);
```

**Comment by brotkrueml** [comment]
Yes you are right, if you like you can provide a pull request.
