### ISSUE TITLE
Update external test tool link shown in admPanel

### ISSUE THREAD

**Issue by AMartinNo1** [brotkrueml/schema#56]
Currently the button in the admPanel links to https://search.google.com/structured-data/testing-tool which is deprecated. As you're from german I simply paste the german text:

![image](https://user-images.githubusercontent.com/5464339/90249633-1bdb1200-de3b-11ea-9289-52652392389e.png)

> Das Testtool für strukturierte Daten wird eingestellt. Zur Überprüfung von strukturierten Daten für die Google Suche empfehlen wir jetzt den [Test für Rich-Suchergebnisse](https://search.google.com/test/rich-results?utm_campaign=sdtt&utm_medium=message). Damit erhältst du noch genaueres und umsetzbares Feedback. Weitere Informationen zur Einstellung des Tools findest du in [unserem Blogpost](https://webmasters.googleblog.com/2020/07/rich-results-test-out-of-beta.html).

Todo:

- [ ]  Check if the new tool allows posting json data
- [ ]  If supported, migrate. Else ???

**Comment by brotkrueml** [comment]
The link to the Rich Result Test is already implemented in master: https://github.com/brotkrueml/schema/commit/eeff54cf90a41ebc41cff378c860576118729023
Docs: https://docs.typo3.org/p/brotkrueml/schema/master/en-us/AdminPanel/Index.html

The next extension version 1.9 will be released perhaps next week. I am waiting for the upcoming release of the schema.org vocabulary (version 10), which is expected mid-August.

Personally, I don't like the RRT (it is Google opinionated and confusing), so the link to the Structured Data Testing Tool will be available until it ceases to exist. Sadly, no other service I know about by now which just parses a JSON-LD like the SDTT.
