### ISSUE TITLE
newline in meta description results in an error

### ISSUE THREAD

**Issue by ste101** [brotkrueml/schema#70]
If the is a newline in meta description this error will be shown in HTML:
`Decoding the string to json didn't result in a array. Please check if 'decodeOptions', 'addSlashes' and 'stripSlashes' should be further specified. `

**Comment by brotkrueml** [comment]
@ste101 Can you give a scenario, how this error can be reproduced? I set the meta description of a page to a multi-line text and added this in a Fluid template:
```
<schema:type.thing description="{data.description}"/>
```
But everything is fine.

**Comment by ste101** [comment]
Sorry I wasn't accurate enough, a newline in the page meta tag description field.

**Comment by brotkrueml** [comment]
I don't get the error with version 1.12.0 and master. This is my description:

![image](https://user-images.githubusercontent.com/2566282/126040083-a1526e49-f1dc-49ee-afc3-e6607c6b8074.png)

This the resulting markup:
```
{"@type":"Thing","description":"Some\r\n\r\ndescription"}
```

No error on website level and no error on validation level (validator.schema.org).

**Comment by brotkrueml** [comment]
Are you sure the new line is the problem? Perhaps you have other characters in the string (maybe not visible) which throws the error.

**Comment by brotkrueml** [comment]
What is your actual code to generate the markup? Can you provide an example (with text)?

**Comment by ste101** [comment]
Sorry, my fault. It was a problem of another extension.
