### ISSUE TITLE
`No valid attribute "applicationType" found in request object` when opening the reports module

### ISSUE THREAD

**Issue by simonschaufi** [brotkrueml/schema#72]
Backtrace

```
- private/typo3/sysext/core/Classes/Http/ApplicationType.php:72
- private/typo3conf/ext/schema/Classes/Adapter/ApplicationType.php:24
- private/typo3conf/ext/schema/Classes/Hooks/PageRenderer/SchemaMarkupInjection.php:49
- private/typo3/sysext/core/Classes/Utility/GeneralUtility.php:3475
- private/typo3/sysext/core/Classes/Utility/GeneralUtility.php:3372
- private/typo3/sysext/core/Classes/Page/PageRenderer.php:2694
- private/typo3/sysext/core/Classes/Page/PageRenderer.php:1850
- private/typo3/sysext/core/Classes/Page/PageRenderer.php:1704
- private/typo3/sysext/backend/Classes/Template/ModuleTemplate.php:381
- private/typo3/sysext/reports/Classes/Controller/ReportController.php:116
```

**Comment by brotkrueml** [comment]
Hi @simonschaufi,

thanks for the report. But I can't reproduce it with schema 2.0.1 and TYPO3 v10.4.20 and v11.3.3. Can you give more information which versions you use and in which report the error occurs?

A core functionality is used:
https://github.com/TYPO3/typo3/blob/master/typo3/sysext/core/Classes/Http/ApplicationType.php#L65
which has a comment when throwing this exception:

    Request object has no valid type. Type is set by the Frontend / Backend / Install
    application. If it's missing, we've not been called behind a legit TYPO3 application object.
    This is bogus, we throw a generic RuntimeException that should not be caught.

Do you have something "special" in your installation?

**Comment by simonschaufi** [comment]
With some debugging I figured out that the `solr` extension messes up the `$GLOBALS['TYPO3_REQUEST']` right here: https://github.com/TYPO3-Solr/ext-solr/blob/master/Classes/FrontendEnvironment/Tsfe.php#L90-L97. Since you just take the global `TYPO3_REQUEST` object, I don't know how this could be fixex since I believe it's a bug in solr.
