### ISSUE TITLE
[BUG] Multiple types set dynamically

### ISSUE THREAD

**Issue by ste101** [brotkrueml/schema#80]
Setting multiple types like this works:
`TypeFactory::createType('Product', 'Service');`

But if I want to set them dynamically through a variable I'm getting errors:
e.g:
```
$types = "'Product', 'Service'";
TypeFactory::createType($types);
```
I tried every writing, also arrays don't work.

**Comment by brotkrueml** [comment]
Use argument unpacking:

    $types = ['Product', 'Service']
    TypeFactory::createType(...$types);

See: https://www.php.net/manual/en/migration56.new-features.php#migration56.new-features.splat

**Comment by ste101** [comment]
Thank you for your help
