### ISSUE TITLE
[FEATURE] exclude custom doktypes from breadcrumbs

### ISSUE THREAD

**Issue by medarob** [brotkrueml/schema#84]
### Is your feature request related to a problem? Please describe.

We have a mega menu with different columns like:

```
Column 1       Column 2
Link1-1        Link2-1
Link1-2        Link2-2
Link1-3        Link2-3
```

![grafik](https://user-images.githubusercontent.com/33951787/150975297-3d6e9dba-ebad-4ee4-89bd-cd620725fd73.png)

The column headline (Column X) is not clickable.
In the backend those Columen headlines (black icon) are custom doktype pages (110). So, these pages are not rendered as links in the menu but as headlines. They are also not rendered in the breadcrumbs on the pages itself but are included in the JSON-LD schema definition for breadcrumbs.

### Describe the solution you'd like

Maybe it's possible to exclude custom doktypes via a TypoScript configuration like
tx_schema.config.breadcrumbs.excludedDoktypes = 110, 199, 254, 255

### Additional context
Currently the following doktypes are predefines to omit from the JSON-LD breadcrumb generation:
        PageRepository::DOKTYPE_RECYCLER,
        PageRepository::DOKTYPE_SPACER,
        PageRepository::DOKTYPE_SYSFOLDER,

If a TypoScript configuation could be added/used for this purpose, maybe it's possible not to hardcode those doktypes but rather make a default TypoScript configuration like:
tx_schema.config.breadcrumbs.excludedDoktypes = 199, 254, 255

which then could be extended or overriden in the custom extension via TypoScript.

**Comment by brotkrueml** [comment]
@medarob The setting to exclude doktypes is now in the extension configuration, if you like you can test against current main branch.
See also documentation: https://docs.typo3.org/p/brotkrueml/schema/main/en-us/Configuration/Index.html#automatic-embedding-of-the-breadcrumb-markup-into-the-page-exclude-additional-doktypes

**Comment by medarob** [comment]
Thank you.
This works for me :)

**Comment by brotkrueml** [comment]
@medarob Changed master branch to main (if you use it in your project). You can also require schema in version `^2.3@dev`, that's independent of the branch. Just remove the `@dev` part when the stable is out.

I'm waiting for the next release of schema.org to come out (scheduled for January, but mostly they are 2-3 weeks late) to tag version 2.3.
